Test loading failed: Error: Process exited with code 4: ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: --cov=qsppack
  inifile: /Users/jameslarsen/Desktop/LBL/qsppack/pyproject.toml
  rootdir: /Users/jameslarsen/Desktop/LBL/qsppack


Error: Process exited with code 4: ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: --cov=qsppack
  inifile: /Users/jameslarsen/Desktop/LBL/qsppack/pyproject.toml
  rootdir: /Users/jameslarsen/Desktop/LBL/qsppack


	at ChildProcess.<anonymous> (/Users/jameslarsen/.cursor/extensions/littlefoxteam.vscode-python-test-adapter-0.8.2/out/src/processRunner.js:27:32)
	at Object.onceWrapper (node:events:633:26)
	at ChildProcess.emit (node:events:518:28)
	at maybeClose (node:internal/child_process:1104:16)
	at Socket.<anonymous> (node:internal/child_process:456:11)
	at Socket.emit (node:events:518:28)
	at Pipe.<anonymous> (node:net:343:12)


Stacktrace: 
	at S.syncTopLevel (/Users/jameslarsen/.cursor/extensions/ms-vscode.test-adapter-converter-0.2.1/out/extension.js:6:3)
	at h2.value (/Users/jameslarsen/.cursor/extensions/ms-vscode.test-adapter-converter-0.2.1/out/extension.js:3:4541)
	at C.B (file:///Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:2391)
	at C.fire (file:///Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:2609)
	at h2.value (/Users/jameslarsen/.cursor/extensions/hbenl.vscode-test-explorer-2.22.1/out/hub/testHub.js:53:43)
	at C.B (file:///Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:2391)
	at C (file:///Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:2461)
	at C.fire (file:///Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:2678)
	at PythonTestAdapter.<anonymous> (/Users/jameslarsen/.cursor/extensions/littlefoxteam.vscode-python-test-adapter-0.8.2/out/src/pythonTestAdapter.js:89:35)
	at Generator.throw (<anonymous>)
	at rejected (/Users/jameslarsen/.cursor/extensions/littlefoxteam.vscode-python-test-adapter-0.8.2/node_modules/tslib/tslib.js:115:69)